### ISSUE TITLE
Project improperly set to role name when applying additive roles via project_roles variable.

### ISSUE THREAD

**Issue by heiny** [terraform-google-modules/terraform-google-service-accounts#30]
https://github.com/terraform-google-modules/terraform-google-service-accounts/blob/master/main.tf#L49-L55
This code should be:
`project = var.project_id`

Apologies for not submitting a PR directly, I'm currently ill equipped to do so.

**Comment by morgante** [comment]
This is actually intentional, as from the example you can see that the role is meant to include the project name: https://github.com/terraform-google-modules/terraform-google-service-accounts#usage

The intention is to allow granting roles on multiple projects.

**Comment by heiny** [comment]
Thanks, RTFM!
