### ISSUE TITLE
Allow per-SA descriptions

### ISSUE THREAD

**Issue by roscoejp** [terraform-google-modules/terraform-google-service-accounts#39]
SA descriptions should allow for list format similar to names so that each uniquely created SA can have a unique description. The current module only allows one description for all service accounts.

**Comment by morgante** [comment]
Yes, this seems like a reasonable addition. I will put it on the backlog and would be happy to review a PR if someone wants it sooner.

**Comment by roscoejp** [comment]
I'll get working on this later today or tomorrow and'll have a PR out for y'all. I assume there's no problem with the variable type change (string -> list) as long as the module version gets updated?

**Comment by morgante** [comment]
@roscoejp I suggest we actually add this as a new `descriptions` variable which will override the `description` if provided, so this change is backwards-compatible (and simpler).
