### ISSUE TITLE
Output refers to sensitive values

### ISSUE THREAD

**Issue by andreevym** [terraform-google-modules/terraform-google-service-accounts#45]
Error: Output refers to sensitive values
│ 
│   on outputs.tf line 32:
│   32: output "key" {
│ 
│ To reduce the risk of accidentally exporting sensitive data that was
│ intended to be only internal, Terraform requires that any root module
│ output containing sensitive data be explicitly marked as sensitive, to
│ confirm your intent.
│ 
│ If you do intend to export this data, annotate the output value as
│ sensitive by adding the following argument:
│     sensitive = true

**Comment by morgante** [comment]
I believe this was a bug in an earlier Terraform version. Please upgrade to the latest version and share your Terraform config.
