### ISSUE TITLE
Extraneous dollar sign in "keys" output

### ISSUE THREAD

**Issue by savvykms** [terraform-google-modules/terraform-google-service-accounts#49]
There exists an extraneous dollar sign (`$`) in the `keys` output, thus escaping the start delimiter of the the (unnecessary) string interpolation by converting `$${` into a literal `${`. This results in a map of output of the exact string as `${base64decode(google_service_account_key.keys[v].private_key)}`, which is surely not the intended output.

I believe this is an unintentional regression introduced in commit 92cac5bf7908e2ee8a44d4d86b6e31548c1f60f3, when the template_file data source was removed and its rendering logic replaced. This, in turn, ended up in the 4.0.1 and later releases.

**Comment by morgante** [comment]
Thanks, opened a PR to fix: #50.

**Comment by savvykms** [comment]
Wow, that was fast! I was going to get a PR together in a bit.
