### ISSUE TITLE
Flagging the keys output map as sensitive prevents its use in certain cases

### ISSUE THREAD

**Issue by mwallace582** [terraform-google-modules/terraform-google-service-accounts#62]
Hi,

I've been trying to use this terraform module along with a `local_file` resource to export JSON key files as part of the `apply`. The exported files themselves are stored in a git-crypted directory for security reasons.
```
module "new_service_accounts" {
  source        = "terraform-google-modules/service-accounts/google"
  version       = "~> 4.0"
  project_id    = local.project_id
  names         = ["test1", "test2", "test3"]
  generate_keys = true
}

resource "local_file" "service_account_credentials" {
  for_each = new_service_accounts.keys
  content  = each.value
  filename = "./credentials/${each.key}.json"
}
```

When I try to run `plan` or `apply`, I'm presented with the following error:
```
 Error: Invalid for_each argument
│ 
│   on service_accounts.tf line 15, in resource "local_file" "service_account_credentials":
│   15:   for_each = module.new_service_account.keys
│     ├────────────────
│     │ module.new_service_account.keys has a sensitive value
│ 
│ Sensitive values, or values derived from sensitive values, cannot be used as for_each arguments. If used, the sensitive value could be exposed as a
│ resource instance key.
```

The error is a result of the following line, which tags the `keys` output value as sensitive:
https://github.com/terraform-google-modules/terraform-google-service-accounts/blob/c6081e22ac89798ed8d51cd11f15225ed18bf618/outputs.tf#L78

The terraform error message claims that the risk of using sensitive values in `for_each` statements comes from the fact that the resultant resources will be named according to the map's keys (not to be confused with the map's values, which _are_ service account keys). The keys themselves are just the service account name, and thus not particularly sensitive. For this reason, I think it's worth considering removing the `sensitive` attribute of this output value entirely, although perhaps there's another risk here which I'm not aware of.

Thanks,
Matthew

**Comment by bharathkkb** [comment]
Thanks for the report @mwallace582 
IIUC the output keys have values which are the SA keys. Since this op is of type map(string), I am not aware of a way to just remove sensitive attribute for just the map keys. However for your use case you can the [nonsensitive](https://www.terraform.io/language/functions/nonsensitive) function to extract just the keys.
