### ISSUE TITLE
Set up CI (Update Int testing to use Cloud Build)

### ISSUE THREAD

**Issue by Jberlinsky** [terraform-google-modules/terraform-google-service-accounts#7]
This module is not yet covered by CI, which means we don't have a consistent way to ensure that integration tests pass before merging PRs (for an example of this being problematic, please see https://github.com/terraform-google-modules/terraform-google-service-accounts/pull/6).

**Comment by aaron-lane** [comment]
This requires defining a Cloud Build pipeline and executing the existing tests.

**Comment by averbuks** [comment]
Done by #16
